FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
WORKDIR ./
COPY package.json yarn.lock package-lock.json ./
RUN npm install
COPY . .
CMD ["npm", "start"]
RUN npm run build

FROM nginx:stable-alpine
COPY /build /usr/share/nginx/html
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
