version: "3.7"

services:
  client:
    build: .
    image: loss-tracker-client
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    working_dir: /client
    volumes:
      - ./:/client

