# Build stage
FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
WORKDIR ./
COPY package.json yarn.lock package-lock.json ./
RUN npm install
COPY . .
#RUN npm run build --production
EXPOSE 80
CMD ["npm", "start"]
