version: "3.7"

services:

  client:
    image: node:16.18-alpine
    stdin_open: true
    tty: true
    command: sh -c "cd client && npm start "
    ports:
      - 3000:3000
    working_dir: /client
    volumes:
      - ./:/client
    links:
      - server

  server:
    image: node:16.18-alpine
    #network_mode: host
    stdin_open: true
    tty: true
    command: sh -c "cd server && npm run start"
    working_dir: /backend
    ports:
      - 5005:5005
      - 3005:3005
    depends_on:
      - "mongo"
    volumes:
      - ./:/backend
    environment:
      - Port=5005

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=sfkost
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

volumes: 
  mongo-db:
