apiVersion: v1
kind: Service
metadata:
  name: loss-tracker-nginx-client
  namespace: losstracker
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    run: loss-tracker-nginx-client
  type: ClusterIP
