apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: losstracker  # Ensure this matches your namespace
roleRef:
  kind: ClusterRole
  name: traefik-role  # The ClusterRole that has the necessary permissions
  apiGroup: rbac.authorization.k8s.io
