# Traefik LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: losstracker  # Change this if Traefik is in a different namespace
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: traefik # Ensure this selector matches the label of your Traefik pods
  type: LoadBalancer  # Expose Traefik externally as a LoadBalancer

---

# Middleware to rewrite /api paths
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rewriteapi
  namespace: losstracker
spec:
  replacePathRegex:
    regex: "^/api/(.*)"
    replacement: "/$1"

---

# Ingress for /api/socket
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socket-ingress
  namespace: losstracker
spec:
  ingressClassName: traefik
  rules:
    - host: mlstatstracker.org
      http:
        paths:
          - path: /api/socket
            pathType: Prefix
            backend:
              service:
                name: load-balancer-server
                port:
                  number: 5005

---

# Ingress for /api with middleware to rewrite paths
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-backend-ingress
  namespace: losstracker
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: losstracker/rewriteapi@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: mlstatstracker.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: load-balancer-server
                port:
                  number: 5005

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: losstracker
  # annotations:
  #     traefik.ingress.kubernetes.io/router.middlewares: losstracker/rewriteapi@kubernetescrd

spec:
  ingressClassName: traefik
  rules:
    - host: mlstatstracker.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loss-tracker-nginx-client
                port:
                  number: 80
