apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMzbHRiRzl1T21zek9DTnhWWFZPT1dFeUkyaExhZz09IgoJCX0KCX0KfQ==root@ubuntu-8gb-nb
type: kubernetes.io/dockerconfigjson
