apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMzbHRiRzl1T21SamEzSmZjR0YwWDFCdFpqUnlabUpqWldWdFRqbE9URGhwWnkxcU4xVm9kbUUwV1E9PSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  creationTimestamp: "2024-10-12T08:12:53Z"
  name: regcred
  namespace: losstracker
  resourceVersion: "4190"
  uid: d00f4ccb-e3ae-4b97-94d1-b327b47f6373
type: kubernetes.io/dockerconfigjson
