apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ing
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-cors: "false"
spec:
  rules:
  - host: tracker.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 5005
  - host: ""
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 5005
  - host: tracker.com
    http:
      paths:
      - path: /socket(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 3005
  - host: ""
    http:
      paths:
      - path: /socket(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 3005
  - host: tracker.com
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: loss-tracker-nginx-client
            port:
              number: 80
  - host: ""
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: loss-tracker-nginx-client
            port:
              number: 80
