apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ing
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Upgrade, Origin, Connection, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://167.235.139.154"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    #nginx.ingress.kubernetes.io/websocket-services: "app-sockets-cluster-ip-service"
    nginx.ingress.kubernetes.io/websocket-services: "load-balancer-server"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $forwarded_client_ip "";
      if ($http_x_forwarded_for ~ "^([^,]+)") {
        set $forwarded_client_ip $1;
      }
      set $client_ip $remote_addr;
      if ($forwarded_client_ip != "") {
        set $client_ip $forwarded_client_ip;
      }
    nginx.ingress.kubernetes.io/upstream-hash-by: "$client_ip"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - host: tracker.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 5005
      - path: /socket(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 3005
      - path: /socket
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 3005

  - host: ""
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 5005
      - path: /socket(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 3005
      - path: /socket
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 3005


  - host: tracker.com
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: loss-tracker-nginx-client
            port:
              number: 80
  - host: ""
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: loss-tracker-nginx-client
            port:
              number: 80
