version: "3.7"

services:
  server:
    build: ./ 
    image: loss-tracker-server
    stdin_open: true
    tty: true
    command: sh -c "npm start"
    working_dir: /backend
    ports:
      - 5005:5005
    depends_on:
      - "mongo"
    volumes:
      - ./:/backend
    environment:
      - Port=5005

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

volumes: 
  mongo-db:
