version: "3.7"

services:
  server:
    image: node:16.18-alpine
    #network_mode: host
    stdin_open: true
    tty: true
    command: sh -c "npm run start"
    working_dir: /server
    ports:
      - 5005:5005
    volumes:
      - ./:/server
    environment:
      - Port=5005

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=sfkost
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

volumes: 
  mongo-db:
