apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loss-tracker-ingress
  namespace: losstracker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http: 
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: load-balancer-server
            port:
              number: 3005
      - path: /client
        pathType: Prefix
        backend:
          service:
            name: load-balancer-client
            port:
              number: 80
