name: loss-tracker-ci

defaults:
  run:
    shell: bash
    working-directory: cd ./server
    
on:
  pull_request:
    branches: [ master ]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Changing working_dir
        run: ./server
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with: 
          node-version: 18.13
      - run: npm install .
      - run: docker build -t loss-tracker-server .
