name: loss-tracker-ci

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 18.13
      - name: server
        working-directory: ./server
        run: |
             npm install
             docker build -t loss-tracker-server .
             docker push symlon/loss-tracker-server:latest
