name: loss-tracker-ci

on:
  workflow_dispatch
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.13
          cache: npm
      - name: server
        working-directory: ./server
        run: |
             npm install
             docker build -t loss-tracker-server .
             echo $(docker image ls)
             docker push symlon/loss-tracker:latest
