name: loss-tracker-ci

on:
  push:

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      - name: Install dependencies
        working-directory: ./server
        run: npm install
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Set up Buildx builder
        run: docker buildx create --use
      - name: Build and push server image
        working-directory: ./server
        run: |
          docker buildx build --platform linux/arm64 --output type=docker -t symlon/loss-tracker:server .
          docker push symlon/loss-tracker:server

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Vite and build client
        working-directory: ./client
        run: |
          npm install -D vite
          npm install
          export $(cat .env | xargs)
          export REACT_APP_SOCKET_HOST=${{ secrets.REACT_APP_SOCKET_HOST }}
          npx vite build
      - name: Build and push client image
        working-directory: ./client
        run: |
          docker build --platform linux/arm64 -t symlon/loss-tracker:client -f production/dockerfile .
          docker push symlon/loss-tracker:client
